apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:vbbewU1i6uqAWV/ehXmBd+xt,iv:dTt8rW/lOQLLifJEWNbSyrtS/BhElIE6xwT84dVXlf0=,tag:h0TXV3w4iwausfS8nf50TQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:YW36SiXBRqdrMZuKF8NvX83v6y/4J7nhomSCJ+DQuye5rXKrIQ==,iv:IjIBnrhucOh8nvBfLFDKokCpyMujfdOp6r5by+FDGtU=,tag:KrB4VfZIh3K4syYxG9eMEQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:RQKBS0/Jw8imKg4960FGcg==,iv:YH/fVulVGKOYyqGHyUWFJKNpuszDfSb2E4JBEOMnVuQ=,tag:ne8BvMsxAxOAKiSMfsfwZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV09sSlBwS2lDTUd4UkRk
            aWNaaEtSOTlNb0dnTWg3Q0RRTjIzMytJaVZZCk4yaE9KVjFsUEV2YTF3a2Q0L1Fq
            ekhaeE92dTFaT2cySkY4L0NMQUw1UkUKLS0tIGpIbjV4TGhuaU96V3VaTHErVXlt
            STV4Q3hHMEowaDcxSjh1TnV3ZUwxcTAKJ6tj6SgTjRf8sC0/MoLpNpez6N/VR9Xm
            pNlTsDd1mZ0OepFeusDncFkp09Sm1sNQgYv5LME4BBmxFLicJTR02A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T22:35:32Z"
    mac: ENC[AES256_GCM,data:8cwvU652x83weEWqOb5g5+Twp9nUOxxMNEhOJyuJxyk0AuedTm3uYyveQixbQqMOih5+KNGOt8r+eNJpaguhQfHOlBE1obm9pF+z/QsG3ZIeM3YmqcBFHh9KctVDPKL2p27ma/ES/Dp2q87RcM2n5iyl8Y6Ycc4cA/rR7Woex7o=,iv:ACuWznPI733DaNAv0q9bjQeGlh2x/f3nDMR4eGyf84A=,tag:6LI+LAtuyT5jATuP58GwSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
