---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: www
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: apache
      version: 9.6.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    disableWait: true
    #    remediation:
    # retries: 3
  upgrade:
    # cleanupOnFail: true
    disableWait: true
    # remediation:
    # retries: 3
  uninstall:
    keepHistory: false
  values:
    cloneHtdocsFromGit:
      enabled: true
      repository: https://github.com/tomsnj/www-test.git
      branch: main
    image:
      repository: bitnami/apache
      tag: 2.4.57-debian-11-r14
      debug: true
    controller:
      strategy: RollingUpdate
    service:
      main:
        ports:
          http:
            primary: false
            port: 80
          https:
            enabled: true
            primary: true
            port: 443
            protocol: HTTPS
    probes:
      liveness: &probes
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
      readiness: *probes
      startup:
        enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: video-input-antenna
          hajimari.io/info: GS Farm Website
          nginx.ingress.kubernetes.io/enable-global-auth: "false"
          ingress.kubernetes.io/whitelist: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          nginx.ingress.kubernetes.io/backened-protocol: "HTTPS"
          #          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
        hosts:
          - host: &host "www.gs-farm.net"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 50Mi
