kind: ENC[AES256_GCM,data:5jPyjloe,iv:m2qT+0VSeS/P2dWFByDwxu2oh5FldW7q1KjviY58fT8=,tag:XZa+lB+L1x6hPwArkBjhlQ==,type:str]
ansible_user: ENC[AES256_GCM,data:fqm+QMLG,iv:IpkRE/cMMSJk/b+gXNXjH4MqHHB/6jOsM7np4vygQro=,tag:FhhBCfCUAPkQq5dMvF9J1w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QrktcZ1nPJjSAKDDuAjzNP0T4Q==,iv:KCrIQYMJvVhM7PJEGNpK/QsuZnjDN96ynRxZasz1anc=,tag:gY91OPGuQFMhzPGw2tnBkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Y0UxUlh6dEhPeXdGQTVK
            ZUN4UURuRWoxNHFqRkNEOW8ySTgya3pTbnpVCmRieGFKL0dISXJoZjJSUVBuZkJ0
            bElwYzFIUzJETlRYdk9IeHhVakpMMG8KLS0tIERIQUZXS2RBZTQ0WFZmb3hLWTN4
            cHNPZGRYL295dHM5YXBrblU4TEhPa1kKH7iLrsxAYGroUmKj64to5vHUaPhkkGuX
            MwukWnWvNIAUGWnUaoktbw+U5ZBSl2J6gjaO/rYaM/tDHLsxPpstgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T01:26:22Z"
    mac: ENC[AES256_GCM,data:kn7Qz/EFHFeZZzV8jsw9dO4R2ty0Macrx8mBxGMZB4XqqMmhBUqo18tcQHgU69nfLeT/WQOYlISCVTunwxY9iQybrdhF67RUchujPdFEY0Xq8R/9cf1HVJz79+2OJtUCITbCXXdN60oe9llODTyrIk1t624ElinetBwd3a2YUOY=,iv:DiTx6aLvtnOrO6vcC7yF/lpK5B8IuNQS+39HYO5u97o=,tag:XrL9izZgSPb9CeWfUb2t4w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
