kind: ENC[AES256_GCM,data:dCgcMO0X,iv:mALc7IjeXi64Xs/Hl0rW3edsxE1Dt+QjsFsHPdWPWaI=,tag:VEaMycL0XcMPdZkVWvuutw==,type:str]
ansible_user: ENC[AES256_GCM,data:Bwxf1XYu,iv:YxTw40RFjTWcWjuzCWToCAKaFnq4dSWiUTtZPq5orno=,tag:jJvRTEHdVrtE0BYTnddKfw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:qpBvtV9cq0Oqc4qYmDqMMxZuSQ==,iv:u+5Lkx3TBxpjkwMPDorKzKvYca10/7+wt0nhH1w/pM0=,tag:ZVsOTLOI+2NaiHe+0Spa9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWTFxL0o1N0EweHgvWWdk
            TjFLMXlsSlpiTXNtamNqZ1I4ZCtBR1p5dTNzClptblpueFRtNHVQSGh3bWZpR2tr
            UVBBdFBrenV0MnBsYm1DL2VJNVVyckUKLS0tIG9rbDFwd1I4UEVYaHFJL0FXazdt
            UGV2aTB3RmJBQlVXRlJEV2RweW5YaVkKvtGdDHxU7yatiogF83YUG8PsWTwQx+E3
            86WfU+pTTziQfyElJ+DfyS4LFSl8+kqacRTul9+nzr2KbiCsyA+F+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T01:01:14Z"
    mac: ENC[AES256_GCM,data:sxrHQjlkp9q7u9AsEcoq3VViGIZjHyEXpLXhDNAVpExi/DsuAbAWrd3Kx85i3WlwW6Pdu2h44lg4AScI07D1pYDIr4g7JscvZMDJ7kR7V0G5ssaC+3Ss5PQFBRck1HnsUTQlEnZZeVKk0WFJWDoWR/5/Jnqx+0Jh/4ExZrKXI6E=,iv:S6/IXorfe9UcYuoFWrJOjaDM/AI+SM8wn9B0OQPU3Sw=,tag:cX+Q2MOM233OKF4DJclM8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
