kind: ENC[AES256_GCM,data:avSXxKTe,iv:ZYsJHmHGzYMm5Ut5IOVfNTSqCyORbmIjJ2xvv8kwE6E=,tag:PZEuAzwTKX/DIWGAv6VHxg==,type:str]
ansible_user: ENC[AES256_GCM,data:f87CXqgp,iv:cqubt3Zh97YCEm7Qf4S6fJRtq3xNGOFUK+NQyA51ktA=,tag:zki3ZnWNT3ChwZFZ2m7Khg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:QsLTbnCgf65msbL3msxnAk48Sw==,iv:JignXw0nvOKpSidqsHoTilHDHk9MwZeeTDdG+21u5Ps=,tag:c0mSWAurVnEiWgEKWmADuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBId0VTclpCSUVaK1ZiL3Ir
            TmNQdHE2VWJrSldkK1BGRm5CL1ppNlhPeG5FCk1VWk92eXc4aWhtSkQyR2VCc3RL
            bTRJYU4zbEgvc2k3cTJEWFFrejIreGMKLS0tIHFjTUZVM3lGSWp1YTFncm00cjQ1
            KzZZcjh6cFlXdXgzQXpaUWdmaE4zbjAKtuwQ9TlpLRH+oRFKSck1wK6jcL2MmkA8
            1j+ItKZ6WsAouluuYh7VLASQsCs176I3h4mVfasY0GXTT2E0GBAzIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T22:01:00Z"
    mac: ENC[AES256_GCM,data:IIg6wrITQt+1f4nuhONjfXkrLvudYnpcHQJcaw3yUcGhoCK58xcyMl8bqFXyGDqC4AlkO/Jb+U7I6Y/wNS1V48fy3EFHGeoXN/oBBhvXjabIOlT7awuROpVVu9z4nN1X9/OmAoK+ESmoQpntI+NnCzbNmI21fGwYHwtdq1E8jFE=,iv:0nlL/eOHvUoZqxtfAYgaUtCgGjuQNmbMSBBwQhBh5GU=,tag:zfLcWyPEZoULw7r55jG+kg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
