kind: ENC[AES256_GCM,data:1gUWklWN,iv:qAFa5pse+YI7crKid/a4y6slZjBscO1ObnNFQaMewYY=,tag:3vjqH1WfWdLs6LEYwTtW+w==,type:str]
ansible_user: ENC[AES256_GCM,data:+lhS0TQl,iv:JaC+ugyPF+b1IpfpXFoT0sZ+q18M/MDJ50mWwpF4dRg=,tag:/8bAuBv4Zwth+Ikfo5hdtA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:lpZcO504HuA6T7Ls05lEMgCw4g==,iv:/7q1sVvlph4YuN+yYn/O5MFh9wPBVoCMvnFwLcwikK4=,tag:mJE176SOdrhqg+xBE45K4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTmhydXVGSElwVFNoQUox
            bmpoK0UxMGJvQkRUakd4SWVndkpFY0pXMVdvCkpqanR4dFVkL2hlQ0NIZkwwZnow
            UU9LeHhXajdZbGlwQytOVFB5cnMrdUEKLS0tIHdRa2tMOGpVaS9zL0tTTk5XTDRX
            OEdoYldYSSs3djJHdlNaN0JmUUI2d2MKw3BuwM49REhSmh9bB6N3Ir8vM8rxD2ZQ
            U+Wh6NOvKopdbT7/TGMMOv7Vd1PrtAoOMZu65QUrftBUOpqunEXq0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-27T23:07:07Z"
    mac: ENC[AES256_GCM,data:zNCpf48BrjYhQ9Z1lTfJaexyoYJgMtPlVXcuzZO2wvX89SuikgyGumPhbS7QqV4+r3M4k/0mbk6ExmChufUZil661In8/N0kE1+V/lAEFOZKQjW+RU7EOP2eAd3t+0bUW30L5ox/Yhf5/8oVpZDwb6f3fHneZggkDNwn3Kr7iXU=,iv:I/nDplWSYDPZpw+2w/9RwLNRjjAfRhHGTgZ+M84we+0=,tag:QlIIDTk2IfDgB0gLPwLyyw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
