kind: ENC[AES256_GCM,data:zKWWmZHW,iv:QAvI3R8HEZ0z7DBHuEqGkB2B0DUMrDsfQBxoYkk/7RY=,tag:7hO/rIZ6pRfqw/3a+a3kqA==,type:str]
ansible_user: ENC[AES256_GCM,data:ROUJLQEx,iv:RkuC9BjPiKbJYvHo2CcWIka+PybWEUZUYlfYg/yZJwg=,tag:5+M862hHhxON8ptsf9enfg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:FIq5jxK/O6w11OtOppOHDTDgIQ==,iv:SxhQ7FHy3sxsVNqqFXhFhFqoGA7cuFKO0ulJT204kz8=,tag:G+WSHwG1bI3pnTRLhdQNiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5djlvcjdNNHRJQkp2ODJP
            YmhOdk5ySW90Q05DQ0xBWXVxRXI0SnJQN21BCkYyY0Q4Z1cwbCs5UWc3SWJwcVVa
            cWNFSXg1anBKTTJ1WEc0MmxuUVhPOGcKLS0tIFdRSmZOYXZXVzRldWlyR1hSQk9N
            MzgyRkFMNmhvZVcraWNRN3hlTStLT2MKLZnWwzPbBZ1JxSJLMyklVdFKJJddHVRZ
            eB3P9GiaqSJccFQfrFZMpBIQLbrQi5ldPblWAt+IHRvM7S1t+yjHlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T01:26:22Z"
    mac: ENC[AES256_GCM,data:B23H79Zh9fKGLVBwzNyjVRhgb4Pes0yEZkWdoT7IHUP6uBwWfh1qMGE3Co3ztGDsOUHlxY6Tkld1O8c3Rn7zqiWGA2ltVuleNNazuNR31/nCT9ljaUuOL/FgDG1w4WCcNG8oyEYyBzfcm0hAEXwgKKkXUE5PbLKx22Eqn3JU7Og=,iv:+bel4RfUTFEh+LTcoJCITcdH54410pQwgC5AuynFlB4=,tag:qcS4xbmWOIZzxSdlhvweiA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
