kind: ENC[AES256_GCM,data:P27ezVvB,iv:LxWz3T70VJLmmgl67aqdlVwepQ7diPy1/QEx+Ceh9jY=,tag:VvD56pYStqoWZLhetnJ1PA==,type:str]
ansible_user: ENC[AES256_GCM,data:UBer5/fV,iv:DF3FfaSCQNUh6HzxFZ+58nv47Q69Es1S03KSPd5XOGg=,tag:K8Ge5pr48qTDxq88Hn3Xzg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:7GNwFDvLX5rSV5FG1HSR8q/94A==,iv:AQzHyLYjoQ78qNIZGkA80UDh0MKZFN+c9I1dN+FMOx4=,tag://Edb0KKHwGV1CB05M+xbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT2ZBZGVMbmNBSmdXZzE2
            SXJFUUVHSzNodnQ5K1QvV3Zlckg3VDRaT1VJCmQySDErMlRnRmNPTGdhOEtpZFZK
            TkV2cW8wU1k0czN2UFVSYlZPdGhCQzgKLS0tIGR2cE5JTTJqR3NvdXBlNjdmYjNY
            VUh0YlVHOGRNY3pEd21HTFV1cDZoTUUKH985XoqzmnQCSILw4BAbiOuz3KwW+msN
            Zd304s8RtIHkgEVQhnzRdhQ7D0gk16vo+Kp/Ljtka56CQT4bcI3Gsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T01:26:22Z"
    mac: ENC[AES256_GCM,data:iWSw8Hfmq3GtQJkIKfu+ZRKJzYiTfmYEjdyYlLiu7z986CYamDphwDiizmI1b7kyyjyeRIRlrrHI6JJMFFtgBiI2WZuGPmoLu5a05lDRN8o4NWlijL4XK/p1LyZVjUK1YSeX8ZoVVAD+7FMlku/9fTM0ejepgVtyPTgsvzZBlI0=,iv:YCUQcMidiYGKTvFU4s2uZicDti7hPbXD3AMiYaw7ZLk=,tag:DrQjinCB8UVtnUsbvY38gQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
