kind: ENC[AES256_GCM,data:0pJyRYU+,iv:7+C65c1PfnVs5p3iiyHFyPz+7QhiSexJEFRXDpCnkOY=,tag:Fpz39H1KQmw3R6kcCoTkPw==,type:str]
ansible_user: ENC[AES256_GCM,data:kyfjP1WW,iv:AArAco/6G340bee3UlblEToNuk83gH+fOs9cw7n/A1w=,tag:rpQLtKCK3n8T0zKoCCjaVw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:GeddGr7EBui6XDhMUeLkvbTQPQ==,iv:GTVQabZe81jCFo6vnXux/Pf6YOCuD6ygaq5kVvO6eBA=,tag:OciqWs7APnMt4Kdwbok/TQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4d21yV0d0S3JHallCS0dJ
            bTJxYlZjZW1rMUVLZDRaM0g4Nk83N0cyZTBvCk11di9XZUc4b0EySzFRRVQ1VFVw
            cnE1L2NMdUdTbkpCa2p6YjQwNVlncmcKLS0tIDEwMU4vUU1RUnhTY1MzbGRaNndV
            dzc5R1kxVTdRNGwyazhLRUpMR01WMDQKMrYz2z2ne6RtlDebgxMJvlWQQG7IW/t8
            d/dLgeXiPDIu74sR5u5TEAY/UY8vosdJCtiD7M5bV22pWB/gT2UfvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T00:48:50Z"
    mac: ENC[AES256_GCM,data:KUYgW1t1WsPJ8e8A9L3GTuqBRrIPgXb4fuagfJVrAo012jGcdgcJy5A4k0lj9NS+BSXvHtbvL+mSzJ3gUkbDQE1zYNCfYlvLVxcos+AwkPHCTGTy6uDNSKBkg+JfhZpALok9PmolaQV0WQPMgHs7dPbx4y2mlNEMJiFBNvZemtQ=,iv:ERuq2IfIOgArSvhdUOIZeY3Hkf6qTCJgSBcYjN7AOWI=,tag:XbhFmPKGnTMPX9rYsc7xvw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
