kind: ENC[AES256_GCM,data:ocd6Ereo,iv:WI1NqtrEZc7TSSJKiAuslxxBVoBiBUAxwRHhXx8PrTA=,tag:jeEDNMtF5lv+c0IT9uWSPw==,type:str]
ansible_user: ENC[AES256_GCM,data:UtghdshR,iv:yMcwtL72mkdqbqwUtda8m1kkvYDi28m4WnRt7/S7E4s=,tag:J2FtbGgM1dx19p1UmGDRwg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:nU0nyeOfOvZ3qnPMKNAWBW0rUg==,iv:0vWUsP+MYCMZhXp0y4REz1oXRAbOJwgae2va5UdALxw=,tag:gaf28LU2EedQi1zpQpAA+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxT1NVNUlscS81bTNaWTFR
            WnBXMUVFNVZydFBGYjMza2g0RGhwRmxQRmo0CmNSU1NJRGRTM1dzVXdiYXdCais5
            Y0t0RW40ejZjemNVbmdQcm9vYjBBdVEKLS0tIHBXSVU2ckpmamhlRDM0WXR5MVhW
            YVFWSGZkaDJ5K091ZGFaTmpabzFzUTgK1WaNdqP7DzwW3sTO/dUNxGyRTuzCjB1C
            l26pzIcsILN9TebKFEzk7PIOtoqqcYY6GCUK1GxueDEvZgIiCEMYJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T22:01:00Z"
    mac: ENC[AES256_GCM,data:VSrhl8Ga82yZx1cZy9NaP9WuRPeIqBP0NPlD2mReLQlyoGoGeu7mZ4d15+L6T2rhO8zD4BKpHWZxzAaDScf0MRumxtxlmOqB3w6S/cwT04zmxJ5AS/efa12BuQujhLfueYMyN2jtFXsiE/60UF1E8s4s3ZXyAlhpoQaH3WFlL3k=,iv:7mH4vh1HIRk0PAjnVvldYUaiJd7BM/tQO8p9vB6x0C4=,tag:E8pT+qfbh2Nb+3naXsHA6A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
