kind: ENC[AES256_GCM,data:1aGsDCny,iv:qNMKgsaNZiGCu/OVbaB3phNJQ6t5RJUHTkbJWIfLP2A=,tag:6w8oQaO7TVdPBl+ZPm2R/w==,type:str]
ansible_user: ENC[AES256_GCM,data:bbtvSczK,iv:GCS3M9mLOguUPIT1EFDrmZNlj/n+fU7HtHD6AOlrvUo=,tag:i9tONIQZhbSPt/RQmHLMNQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:T0S6gKnjE8kUkY4hsMiAX946Cg==,iv:3u4iHAykA0GYpJS2C5i28G7ZLHnuEC1KUtS9u3/LWw8=,tag:JJ+Ydyna6TsnKnGQjeTIYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeHBuV0doWUNZVDBHVkYz
            UjNiNGxhUzBZcFFOcmFZbmlkOVNtTUlaZ0NrCkZJZGhNakc0R3lmZW0zcmRCdFZO
            dnlDSDJjR2VSK2ZMQUR3Q3o2TmZGRzAKLS0tIFAwdDQwaGVlSVNSeHh5cllSNmNE
            VkYza2FmRlVsSm1DQ2MvVlJyN3l2dTAKeNFPLtXv5q+OO6Ic8IYq/HHjYK66jP4Z
            wbEru6PkOkKDjm83kaCYJ8iAtrRMnbvDzFIu3sA3+zEfu7Lhe2/rQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T00:48:50Z"
    mac: ENC[AES256_GCM,data:4M4/1fPS849735+rVVOXUPRCS6TQ+rcj7nCHnz4DGUD+0IS1sVtd472MZYOnAIkD1LwjulaVOAvo4yOyOtj4Pi2te/o7Uu/eWcxjc7EHf5j7YdR+P+XIcP/z6j+CsEVchtffazgA2vNSLUqMMeTfNs8DnXukJHhRqqNjXzNlOQ4=,iv:eHhHdSMOAxZ3qiJecarlEavkl3YCJuicRmn4VlESy4U=,tag:DLm4H5dSDmhowNzXy4XwBA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
