apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Kgjvy0Q5T7KpdSG0QQAgbqGjbXaQMy53g6tRL3zvjGFpuVcsddEHnw==,iv:MZamPc1pDHqsN1xmLzsCgWoETSag012hXErVsj6u7Jo=,tag:7VkJ/O0oum/HUZklTMtnvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbS8vS3VJZ2FSQy9uTmFq
            MERmVkpEcER1d0pBdktPSksvQVVqOGNnZndjCnlzV2F6U3Yxck9LTFVWMHJYa2tl
            Q2NQdUVqSllFVVpncmFCOVpIZXJFTU0KLS0tIFRSOEdOQlA2T0tRRklYa1JoODV4
            cER4SFNoa3k4L0lpcDUzc0FRMUorNW8KPmY6CMHLIz/eFLQoulXSdviDJTieOEtk
            DWmwwUdpk8bmI7q7wEwQOQTaPJnVwO/hJMhdxgHaEqvP78tCMIMUDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T22:01:00Z"
    mac: ENC[AES256_GCM,data:ZUh2xlIp61xjKcS0WIHSClQgciGNgtYkDr8aCJxzM4XT/TPNplYwrvvcKIJ2RKop/nb7Iyq+sk9B7EtBbCuhVwf829oCXydXmrN0X868nZNvkDU0vzpVOcmfHs/jvVrHCoHhfZ+O7lAeD4WV4Nc4TJbu+nQy7sCoquQoZCQx+Bw=,iv:tX82NrC7VcRdz8o0tBN7sQzIATM7xmgegVbbvyvsrYo=,tag:eo/rlo4bT+18CRkEBLcJuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
