apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:C1hf9UzqoFwAQuMcF5x8D8SkgnpqrsYX0RK9V20CNj7QYwcz9M7vYA==,iv:46uGwe4EifoewL9ZlA4Wd4Btx7u3j3GMUhxqrGS1NqY=,tag:ikbrgYZpa95ED4EkdFfmGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaXptclRqbmwxM3lZckNP
            dUlUaFd6cUtpR3pGUGhEcUttSzNlSlJ2T1hnCmhjODNGVVh3dlBIajZ2bHlmKzEz
            ekxHeUdyeVEvT3MwTTFXT2lvK0c3UWsKLS0tIGllY3pFdlBOcUhSeEkvVWJpRXZ6
            V3NDMUViZG1mQ2NYeGRTVVhuSUNydTgKC0pLwdRTuJvAvpZUVt8XWUI4e4VgWr13
            mcjrejVkSYi6UbF2sLlxfgnMbCh0nOtt4WUBRKuFNEtvzVXY1HXvFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T01:09:48Z"
    mac: ENC[AES256_GCM,data:c2s2xW9aQ5bGVkxDXDm4w+5tTXuLTuoj0gfU90Ht236IuQYmBug7yrPLAozc7iluY9klUvampCdfMe7NzPR+rPOcP6A3i7Ma0yvly0ADy6AEUyc8Gr7S6M0cbUvr6mTSOAcTK3w6jnLxn9h7zUbinYqFEmPtMP3xwsAH/J4nO2g=,iv:Q3Py4HUl0ZD7bkyVWdzuJ8Irbf6nb71hn7tb16YibK8=,tag:OmNaYfm3RBVgN++8arhwtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
