apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:1F0jAsXduJ4kT6vKy8ui1TvKL2bvC5MVoiTSR/0MO+7mPqMCVg==,iv:c30PqhEhPcuyUw4G+DnZu/bcd1mEDMZrflv0ZW1cRts=,tag:brEoImNQKvRjuq3eGWcFDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFc0diUGM5MHRJcmNFaFU5
            MDRWSWFCbjRGSWpVN0YweHYyWFN2V2NubFdRCmlrUm9GalcrMml5dlVDL0wvL2ps
            YjZCSkN4ZUpzRi9PbWxBUEE0VW0yc1UKLS0tIEF6YmVPZFEvYy9uYjREL1pVbHFY
            ZmxERGhVT3hjZGQ3NUZBZXgvZ015ZmsKy9VRlW+xvAGjRJGDrDar/eykGMCkaIFJ
            5hfwcy7+K9QpRnmnudQ5NdcnnuI9SR1N1ZlQQ/YwqgselxMH0PkHIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-26T01:09:48Z"
    mac: ENC[AES256_GCM,data:eMlYSAujV7N9n17+oo+WHst7NEhIWpjr1C8pGEJ5/PlEWnu0FKYvH4eF0kSAKwigWsGKiOBPQ2/5J86K9FV0HpPO1JWbPWDeAO02s8gpXEyPHzx5+Lzc0ma0maEvBqerJIU7MSk5NSIb57/njT+nzKyd2sEacYcoGcoGJGWlMaQ=,iv:54O3nsoMFaQ0ITVBCdvvOFxpJDDMQ8/0WJquS5xyRPk=,tag:HweK6+Mgl/WbhdNLHEReAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
