apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:noEjUZIw5EjDyAu0oqBrp9o5,iv:EsJU/wmDx0TzkuatMNwZjSEGZ8hW18ref1m9hofQ1eM=,tag:G20odAwzLtTp1VCakISJvQ==,type:str]
    api-key: ENC[AES256_GCM,data:8k1HWzpr1Ep1hzQQqurJPsD86qfA1vtw5HCw4vK48BETxYKJzw==,iv:6UkJ0zFyacE3p2KsS4vO9Kbugml5fo+QtKdz/NUh6rc=,tag:+smcjI4F+J7/4b/r4NGSaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIa0IxQ1RjTFZwNVU3NGxN
            V1grTWJHdi96cHB0T09vZSttc0I5dmlkZVdJCk50YXprRlY1SGZPb2FvT0dRdmJi
            UGpJa2c2d0IrZkpZWWtJN2ZhMmdLQ0EKLS0tIG1oWTVSMmpzNWgrZnJiUmdNek11
            cUgzM2wvMXZzSVZubmhna2xBYnNqQ28KMzUJINFenscZPLXqWHXP/7uu+IOBNGoc
            z23l+3ypUibkrTlR+s1HJI+h7Z77oP+d61ZHJCSZN3FETTnPZt6fxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-07T01:19:47Z"
    mac: ENC[AES256_GCM,data:+A43Y4tZeOjQE4lOJTN2y1uZZzly/tz/+fSz95o6zpNEexQbR9KvNl42AFUGVOPdp+dpvhGxFGR4UO/j9qn2xYqePTi87hPO2/49CH8JWAo8zVkfWYChfQIJ+Q5zta2s6BdMdBuhgjLqilC8GypBilf0EGPp3YmNOpP6+OnreGg=,iv:IjAADEYb8P+rafI/N9LnVC8cEqptsFFINgAhzN3D2zg=,tag:RQCnrYpQ0WqAaFBmYWzqcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
