apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:3adK33W3pNE/ta+cJ10mcRek,iv:/oR0P0P9+P65YD74c3wUx7kcvbNvEqjUgIb9CPw1L0Q=,tag:ahsdbvGDltfHgGXS9M6k5w==,type:str]
    api-key: ENC[AES256_GCM,data:g0YmVxMZAXm4Vx31lrUmbC0GyCKEVbVaIYKseBbDKBE7IrjNlQ==,iv:PVAKhaR7CDo1qpy97SMyWgwaW91JD9FEnacKoJXh1Ds=,tag:05TNeccJ8+Qpm24C6ym0rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcVl0S1Z5ZmpjUml0UkZq
            VzVnczYvZDR0OHZ2TnVvaENBNlRTWkI1SXlZClZJdGlzdUd5TVZSYnB4eXN5YzZo
            cTJBZXJocTNleVlBcnRqeFJVTnpJS3cKLS0tIEtpNlQyOXI1YzduaXNlbmsvVjF2
            bnRNYXd3dWFQUnNkdWlrcE50cDNCcTAKflkJsK5/jUTN5mN3OVgGUX06b7hH3FPg
            yU30NkDGPpD7BClvTGbjpaU51ct98gma7K1nR/kCXb7o89LCuU0kbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T00:48:50Z"
    mac: ENC[AES256_GCM,data:O+CkaidWcV6mLIrY7QGCnNh19Ox4uqNbUEyK1XqSoP6gZ1NJBrJ3N4Rq//F+HNeysaOKcTGFxSIDhCarThZGk9wGyUQkX3GakUSNAvlayaTjzRFAAngBdmT2bJhLs70TqGtPgeUJJfmcuMsLTLsim6mc7D1Eaz79y+Cnn6BbJIs=,iv:eAJF0nFoD766xqDLjB41ISr2C36oWyT0zvCR9FpwJ40=,tag:wq1MovGN/WKb7s26hbQcWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
