apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:o5TmiOs5RrWI2CdbiBCfIfam,iv:zudTne4z/aQWE7jBN80S8OmcMp8HQQ5pEZCu9Y6z5qk=,tag:1A6qWbbPExZKpnCltNxyIQ==,type:str]
    api-key: ENC[AES256_GCM,data:laP5iDlp4Q63Sz4WqANCXcVloLXjK/byy0thkbU4pK3Ee4DiWQ==,iv:+GO7rbexb/lY3R7IewKF7QspfylJKszhIsF9OTPodbk=,tag:gaMdr43YN8yKAW6LVW8hig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUkhSd2w1Sys5dHdYOFRn
            SnZ3MmZ2MnJmZ0N3WkZTQ0oyTXFuazNYTEhZCnV5MWVMbmU5Y2plTzRwdmoyREtj
            Z24xQzRiTFFhNkhOdERqWTR2NDE4bmsKLS0tIFhvRDhDVmZHUlNtWGNnQU1GRGo3
            YlNDdlRsR04yYVRSandZc0xEOFRjSzgKPKhDyYz2zRbv1nhyRBxI5pkHgjKuMuej
            oMXTJbOGj/6Y0MYI2eZZJTdlbGYc8OIsp8hS0e+HiLBzVic+rpX/kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T01:26:22Z"
    mac: ENC[AES256_GCM,data:hf1YYhl3Rh6PvGamV1xEHMnYQT4x36TqEth2BFjVdg5QNDm7uZJzXXFakmJQad6/LHy4HLBCyM33zMJ3ch00msZheMxA1HsgGkzlVQCNrOLcdvhhPWTE56kLvLalG1VDHXptzaS7N4rfGj8AqXuKq0tliKNdF6nEdLSxiDgC4QA=,iv:f9k69B6N6qX/Ly7zNTFDV+xXvLqJiOUo+sY0BeUpHwQ=,tag:M5i1yUimfgGNvMki9ikYmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
