apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:mJqMErwjSvO0dSX0/acnJiME,iv:6mBsxU3waPV5uiXcDYZ+BxUREbHLsW+5ViBpJPMsprA=,tag:48wmN6bE+4Mn3Fdm1NgafQ==,type:str]
    api-key: ENC[AES256_GCM,data:l7d8gXF+I2LUYyCLAp6YpKVSuJIEDDqYK3/q0L8mkWcYRPt1mA==,iv:h2VevcXimOVJDigPbOztuigTgqa3nj78qLyqnMv+wFQ=,tag:yHDxMd8Oz0A1AZuV0lAwOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuS3pjQmxZbkhnc3NXR0VB
            aHhzeGFBMlBqVmZPdXl5azBsaE44YTRQY3pBCnJCQTUxU3JnUU0wS29JdzRDc0tr
            ZDVoSklua2pQckNpRVZEbS92TlN5WFUKLS0tIEtJc2ZKSW5BZTZ5ekRnYWVRemk5
            OEg3Q0dyYlFQcFhxUjNRYld0dWlOYVkKKd9TuqMdjV6M+ke4U4Ew28RKXNsoswqo
            dJej5eJuep0k7l+VaJD+rQWuGUhTNLAmzXkW329CIfct6oYUOziD1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-31T21:50:29Z"
    mac: ENC[AES256_GCM,data:ZDNzibEVAI1M89+y9Yabzb75vbc00qLqAub3/LhzrjddFws6X/lAOS3/Y6gWlbM1kX+6+7FEYgyfOb6yGUR/JSNlow3bTymNMxsTtPgzNAZ9kscYEFJFARStN2EGANesv+HPpTwZpZHjzEu0z1NMgQkrHqg04aUUfMVIS7S2o5U=,iv:0gG3D6yrRaj0mruUFJ5NMg+FaFKlCvX7spPh+GyI60g=,tag:q7c5gLAXuwciyi3ZTZAFkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
