---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
    #namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
        #version: 46.8.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    disableWait: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    alertmanager:
      persistentVolume:
        existingClaim: kube-prometheus-stack-pvc
      ingress:
        enabled: true
        className: nginx
        hosts:
          - alertmanager.gs-farm.net
        path: /
        annotations:
        tls:
          - secretName: kubernetes-dashboard-tls
            hosts:
              - alertmanager.gs-farm.net
    grafana:
      persistentVolume:
        existingClaim: grafana-pvc
      ingress:
        enabled: true
        className: nginx
        hosts:
          - grafana.gs-farm.net
        path: /
        annotations:
        tls:
          - secretName: kubernetes-dashboard-tls
            hosts:
              - grafana.gs-farm.net
    server:
      persistentVolume:
        existingClaim: kube-prometheus-stack-pvc
        external-dns.alpha.kubernetes.io/target: "ipv4.gs-farm.net"
      ingress:
        enabled: true
        className: nginx
        hosts:
          - prometheus.gs-farm.net
        path: /
        annotations:
        tls:
          - secretName: kubernetes-dashboard-tls
            hosts:
              - prometheus.gs-farm.net
