---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: prometheus-kube-stack
      version: 46.6.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    disableWait: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    alertmanager:
      persistentVolume:
        existingClaim: kube-prometheus-stack-pvc
    grafana:
      persistentVolume:
        existingClaim: kube-prometheus-stack-pvc
    server:
      persistentVolume:
        existingClaim: kube-prometheus-stack-pvc
