---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - rbac.yaml
labels:
  - pairs:
      app.kubernetes.io/name: rook-ceph
      app.kubernetes.io/instance: rook-ceph
