apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:MlFVpYUHs3dKXyBMUpLkmyicAgoVMhz5uu1zIv6zS1q3LkzAWj2CnS7aoIdHvtv7G+gjwVNaI2Pj7nHQ,iv:ZqujGzIAqraTKNVxELq7Yzcab5X2uCbovLEpWfkFSrs=,tag:+h8vuljpbhx5l3PuudEB5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6T3R3aXh0SmxqekRRbnds
            N0dPcVBaUHpyRlgxdytoVHFBd3c1M1pBb21RCkdqcksxREk3YVU0aXBTcmk2SWJD
            dG9SNlBVaWN1UGFXVjRpWWxVK05OdHcKLS0tIHV2dDF6dzd3cU9LYVI0bHhIUlIy
            aFZncGZweU4yT2RrREtYR2V5NVU1REEKZs3nUj0mDcx7BWuwICbzP+Hx8ThHAlU5
            eRLFCF+PaXcQzTKihCBhc/HGfhwVia8JpWsdsNyblXdjctfHR6BXuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T01:01:19Z"
    mac: ENC[AES256_GCM,data:VH6CgVDSOjBV0C17STbsASsEyFZ47gPkjD4RA6jiPl5t3sJdqM4139pp1gUjDkxI5KT3u/l6b09isHEZ93qvu8f4s1ip37YS+Okg5z5xorF+czEr7jSiSWwaGoy0cYv56KACrqx2EA44TWLLrtsTPzvxXjwjFWFHI46xfF2LP0M=,iv:iet3Wunag3fbFccObL4NsTrywId1oGD5SI1mp/2omEA=,tag:Qix0U0E5I99jkoL6lGaD+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
