apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:/ESHkJH830BaIPzM4xlRbPrqnGSB2QdXutAYr37CiR5I98dTyL0h2+7OSk1zYUS3VSlpqcL7Pn1cZE3/,iv:PtvSdIhNDLYc1BXJfJy9Luj87eRM3fa4Z26sssXhsnA=,tag:9mShEjBHGZd1Eb0NxFBGuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TGVPNFpvQ3B3YjA3eGZR
            WS80MjNobnI4NWVnVThlakc0R29lNi9yeEgwCis0Y3BvdVphY2ZLSTE1dy94TkxU
            TVVtWVdBMDV4VjU5Y2RQcmVEa0JkcDgKLS0tIEtrRER2Q0s1dW10eWFEaE1aaCtj
            S0tJR1dtcDNqa1dVV2RXZHV0bi8vNTAKzWkpA0R52VNs0qlPkT5XzvpsCfZsCZ2b
            YFvfxZHeGC0HPcCuEVC76auLFrz/r0S6D/lWBFs7uFNXkEf12Za5uQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T01:26:22Z"
    mac: ENC[AES256_GCM,data:CJhiGxJfdwKN2qD7vtxA2DDIMEVH2qI/3Tzwm5VRBodDTdU0GblArlE0CKGc9dhD+7KN3citlPXvyLF05pJYdBvz3FOhhS+hvtKIIGaKt2jevKsF7/GsimZr8du8hwrI+GQIS2CYDkHKIAkq6KROYZEfEujfR/a4JhzxmZ9r/EQ=,iv:jXwB81fxb2cRqTxbuZwQauptsDCuyQ+Q2pfldnAacvM=,tag:eAdLpN8KV22/4f8FAtD8Iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
