apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:i7oI0IHMZBcMzQ6arblWBEp/ac/nAr3Y5NGhHcgGIFFXQ1dEc56AeYGNyP6CxNSGu8KFASNrITu34lFK,iv:HkkZFUmUSWhDk6VlFRjlMWRSoow/unyEoIoeV8Nd6dQ=,tag:dNs/57sO/hZx9xg+7hkgPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa3pwbHEwWkV1bmE3M2gy
            dVhlckE4STZVbHRmTkZ2VEFKUHFQZHhtbDB3CmhRYVFCSXE2czkzcndFTGVEanky
            dXordFBSUTByd2tKU1FFNDRRS0FRb00KLS0tIGJkWTdyWWRibSs5T0xSbmhtdVpk
            UnhtaFY0Qzlranh0ai8rdTFkVTViSTQKbNQtGlzKT28W50/rjwQjkcI3P9mUPMg9
            lakGHTpvXMdxXa8YheacvjubLjDG+PjSF+0ZrPssHa5TndqNVCv+mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-27T23:07:11Z"
    mac: ENC[AES256_GCM,data:AJgxcTfMiJOlSxpZef+bHO8qyfXletTW/gtj/ojr0JXg+rck3U1eCKxFwNzv4SrIVrt2yL27eyVaMymdQPmMw8sK4txwR3kNwVc/XXTccx5BkHiq3u+qAUzlj3MSmhYb+pLQF9FFtT04qpLaNjoBAraXiEM/doeDsxZIUr/Iv6U=,iv:PBjoZ87NH27tS0TMSzRvSF+dAkuKOxgjQyXc/7Mo1JA=,tag:+G5FHET9tZxx7ZVEWgOyoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
