apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hWsAa9aLREHlYoA=,iv:ATZ9M0SiYfrFO8Eqd0w8U5zKgAkF+5gHZhM/bRNBwKY=,tag:SMeTIqWjtFHdbHwCZ42MuA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2uMFjGFuG8dSb5Lu3Ouf66/n,iv:xvaTRWwgJZJoT/lujlYdoj2nYF90WGta4UZNY8h/35Q=,tag:ptWlm6QlKnYYHut/oVgOWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRXRvSzJPbVNQVVJ3T3BQ
            YlJyNGF0SllmRXJ2emlPam1yVmhheHR4ZlVBCnJDb2psUzNZOG1jVGxDSTVjdGVX
            ZEtjR0lLRjVmNTY1YzJsTHRYN0NveXcKLS0tIDM0SjN1VW1yN3BSRHhoSUF3MTdI
            K0lBYVluYkk4bG9YSmltNTA4MEF1TmsKGski7o0fIi+bNUC4V9l81TFbngnh7HfH
            UvVnSRuUtlYPhcmXhV8WbKkURSS5zxmWFl2Lz4IxTZH0IrDKKN1JQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-19T00:48:48Z"
    mac: ENC[AES256_GCM,data:dEEzv2b9p7K5w343FvYgPgTV9UP17z0wdyUUOOHjYLuSe11WHZVZrDZKqfh16icHThXPJwcjgKP3D2RHGvRHNFny6oCnuE0JDJ+LcSbbo30kgKG+VqmKCx36UqkgH9KICtmEDx0sHpkYTS8zjMYwX+R+h0n6XeXuXH9yfqqtzp4=,iv:eKMJiBET+L4Vzy31k4MEashmhx6AYS/dDJ9NBmoA7HY=,tag:D2mylXGCHXdT3A5DnSMOQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
