apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:7vrTEYLT4SBWjuc=,iv:VIH6XaxpMwM4PqZGosBTaKNi7tgpTyO8zju/hVgfWTA=,tag:hEZhiwuqQID1R7WQFACcNg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:utNJYJtxUka0dFzV1jKpce4B,iv:f0M0SnGdSsrRwYjW4QqHqMgv5atAtU5prnHtXi3Zy0k=,tag:Mwi+BLdMaGPFZQaMmcOdTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w405rztatml7wa8kmn65szkr3cmreqv5g0cfgwkj292gek2upg6skseqzu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYmNoWUNMdC9pWUIwVHh4
            VDNpQWtkcXpsSXBVOENLUUY4SzZlSGI5Z3pZCmp6aGMrSDdGTjBDSFBJNnNZVklV
            Ykc5ZG9hNHh2a0d4MGRFZklUZFpKek0KLS0tIE45SDFWZ003OVlyc01HTGhRa2oy
            YlRNU3BhMUgxQnYwM0JRRHJKUmdDeWsKj8ijNL0XfGqGWa/VQ8ZBAeUTOmzMJOXu
            h378+dZklqR6GW/Q0+uTDBE+if/khUU9Xslsp5iQ6wxPMU+BRgdjIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T01:01:14Z"
    mac: ENC[AES256_GCM,data:VxXs6Z/XbU8dUsISLfyJB5NLK362iKS++SjN2HFBRvfDbVmy8Nqm8XJM1uHrr8NSsycjYa42NnvZJJdYS1FaY8lwkc9dPq3FDHWYSj2ORCQrbcDoLLLuzh47HXpcppvzwh5uUd6OeT95O+5i6tMvKs7OKyscwclooravtwVc+nM=,iv:apcRVjednYFAYKj39N9PS8gp6alpPHfhEWtA4FJZDz8=,tag:MyfAE7HtB/BoS4jeHwXryA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
