---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2023.5.4
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/goauthentik/dev-server
      tag: gh-main-1672594721-f90a52c7d6fda926b9e6d9845d8ca3030837c224
      #repository: ghcr.io/goauthentik/server
      #tag: 2022.12.1
      pullPolicy: IfNotPresent

    ingress:
      enabled: true
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: login
        hajimari.io/info: Single Sign On for GS-farm.net
        hajimari.io/group: tools
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.org/websocket-services: authentik
        nginx.ingress.kubernetes.io/enable-global-auth: "false"


      hosts:
        - host: "authentik.{SECRET_DOMAIN}"
          paths:
            - path: /

      tls:
        - hosts:
            - "authentik.{SECRET_DOMAIN}"

    authentik:
      # secret_key: #in cret
      log_level: debug

      email:
        host: ${CLUSTER_MAIL_SERVER}
        port: ${CLUSTER_MAIL_SERVER_PORT}
        from: authentik@${SECRET_DOMAIN}
          #host: smtp.gmail.com
          #use_tls: true

      postgresql:
        host: '{{ .Release.Name }}-db-zalando-postgres-cluster-postgres'
        name: postgres
        user: postgres
        # password: #in cret
      redis:
        host: '{{ .Release.Name }}-redis-master'
        #  password: #in cret

    postgresql:
      enabled: false

    redis:
      enabled: true
      persistence:
        enabled: false
      auth:
        enabled: true
        # password: #in cret

    volumes:
      - name: cluster-domain-cert
        secret:
        # secretName: ${SECRET_DOMAIN_CERT}
          secretName: "${SECRET_DOMAIN/./-}-production-tls"
          optional: false # default setting; "mysecret" must exist
          items:
            - key: tls.crt
              path: fullchain.pem
            - key: tls.key
              path: privkey.pem
    volumeMounts:
      - name: cluster-domain-cert
        mountPath: /certs/cluster-domain-cert
        readOnly: true
  valuesFrom:
    - kind: Secret
      name: "authentik"
      valuesKey: values.yaml
      optional: false

#      metrics:
#        enabled: false
#      extraArgs:
#        default-ssl-certificate: "networking/${SECRET_DOMAIN/./-}-production-tls"
#      podAnnotations:
#        configmap.reloader.stakater.com/reload: cloudflare-networks
#      resources:
#        requests:
#          cpu: 10m
#          memory: 250Mi
#        limits:
#          memory: 500Mi
#    defaultBackend:
#      enabled: true
#      image:
#        repository: ghcr.io/tarampampam/error-pages
#        tag: 2.24.0
#      extraEnvs:
#        - name: TEMPLATE_NAME
#          value: lost-in-space
#        - name: SHOW_DETAILS
#          value: "false"
