apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: "${BOOTSTRAP_AUTHENTIK_SECRET}"
  postgres.yaml: "${BOOTSTRAP_POSTGRES_SECRET}"
