apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-cli
  namespace: kube-system
type: Opaque
stringData:
  BW_CLIENTID: "${BOOTSTRAP_BW_CLIENTID}"
  BW_CLIENTSECRET: "${BOOTSTRAP_BW_CLIENTSECRET}"
  BW_PASSWORD: "${BOOTSTRAP_BW_PASSWORD}"
